[package]
name = "redis-postgres-migrator"
version = "0.1.0"
authors = ["Nell Shamrell <nellshamrell@gmail.com>"]

[dependencies.redis_postgres_migrator_redis_lib]
path = "./src/redis_postgres_migrator_redis_lib/"

[dependencies.redis_postgres_migrator_postgres_lib]
path = "./src/redis_postgres_migrator_postgres_lib/"



