[package]
name = "redis-postgres-migrator"
version = "0.1.0"
authors = ["Nell Shamrell <nellshamrell@gmail.com>"]

[dependencies]
regex = "*"

[dependencies.redis_extraction]
path = "./src/redis_extraction"

[dependencies.redis_postgres_migrator_redis_lib]
path = "./src/redis_postgres_migrator_redis_lib/"

[dependencies.redis_postgres_migrator_postgres_lib]
path = "./src/redis_postgres_migrator_postgres_lib/"

[dependencies.habitat_builder_sessionsrv]
path = "./src/redis_postgres_migrator_postgres_lib/builder-sessionsrv"





